# ═══════════════════════════════════════════════════════════════
# Стратегия: discord
# DESC: Для Discord голосовых каналов
# ═══════════════════════════════════════════════════════════════
NFQWS_MODE="nfqws"
NFQWS_QNUM="200"
NFQWS_ARGS="--filter-tcp=443 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fooling=badsum --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-udplen-increment=10 --new --filter-udp=50000-65535 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=n5 --dpi-desync-repeats=6"
